module.exports = {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  ignoreFiles: ['node_modules/**', '**/*.{js,jsx,ts,tsx,json,md}'],
  rules: {
    // style format
    indentation: 2,
    'no-empty-first-line': true,
    'max-empty-lines': 1,

    // style rules
    'no-extra-semicolons': true,
    'selector-class-pattern': null,
    'selector-pseudo-class-no-unknown': [
      true,
      {
        // for CSS Modules
        ignorePseudoClasses: ['global'],
      },
    ],

    // order config
    'order/order': [
      'custom-properties',
      'dollar-variables',
      'at-variables',
      'declarations',
      'rules',
      'at-rules',
      'less-mixins',
    ],
    'order/properties-order': [
      'display',
      'align-items',
      'justify-content',
      'flex',
      'width',
      'height',
      'padding',
      'padding-left',
      'padding-right',
      'padding-top',
      'padding-bottom',
      'margin',
      'margin-left',
      'margin-right',
      'margin-top',
      'margin-bottom',
      'border',
      'border-left',
      'border-right',
      'border-top',
      'border-bottom',
      'word-break',
      'text-algin',
      'text-decoration',
      'line-height',
      'font-family',
      'font-size',
      'font-weight',
      'color',
      'background',
      'background-color',
      'visible',
      'opacity',
      'box-shadow',
      'box-sizing',
      'overflow',
      'overflow-x',
      'overflow-y',
      'position',
      'z-index',
      'left',
      'right',
      'top',
      'bottom',
      'transform',
    ],
  },
}
